# sudo apt-get install ruby1.9.1 ruby1.9.1-dev openjdk-7-jdk unzip zip maven
# get leiningen script from github (apt leiningen too old)
# sudo gem install rake fpm
# install jzmq (dpkg or apt) ... if dpkg, run ldconfig
# TODO: should extract zip for deb, instead of find/cp

version="0.9.0-wip21-ics"

# Gah, no one tagged the version, but master HEAD is 
# mostly unchanged since the version bump
archive="master.zip"
archiveuri="https://github.com/infochimps-labs/storm/archive/#{archive}"
dir="storm-master"

extractartifact="#{dir}/bin/storm"
buildartifact="#{dir}/storm-#{version}.zip"

instdir="inst/usr/local/share"
instartifact="#{instdir}/#{dir}/storm-#{version}.jar"

deb="storm-#{version}-all.deb"

task :default => [deb]

file extractartifact do |t|
  sh "git clone git@github.com:infochimps-labs/storm.git #{dir}"
  sh "chmod +x #{dir}/bin/build_release.sh"
end

file buildartifact => [extractartifact] do |t|
  sh "cd #{dir}; bin/build_release.sh"
end

directory instdir
file instdir => [buildartifact]
  
file instartifact => [instdir] do |t|
  sh "cd #{instdir}; unzip ../../../../#{buildartifact}; mv storm-#{version} storm"
end

file deb => [instartifact] do |t|
  sh "cd inst; fpm -s dir -t deb --name storm --architecture all --depends jzmq --version #{version} --package ../#{deb} --deb-user root --deb-group root ."
end

task :clean do |t|
  sh "rm -rf *.zip #{deb} inst #{dir}"
end
